### ISSUE TITLE
Monitor system energy consumption

### ISSUE THREAD

**Issue by MattiaSilvestri** [MattiaSilvestri/energy-monitor#1]
First thing to do is to find a way to monitor and display in a very simple way the energy consumption of the system. We can can start by displaying it in a terminal, maybe later we can think of adding a GUI.

**Comment by FrnRmn** [comment]
What about that? https://pypi.org/project/pyJoules/

**Comment by MattiaSilvestri** [comment]
It measures the power consumption associated with running a specific python code right? We want to measure the cumulative power consumption of the whole system since the device has been turned on, but maybe it's a good start.

**Comment by FrnRmn** [comment]
True, yet it could be a useful metric (if I run the same piece of code on different hardware it should give me a different result right?) so this could be used to integrate all the various hardware components consumption within a single metric, that should be then still be linked with the actual power consumption tho, maybe it's more complexity for nothing. However it seems not trivial to get raw watt/h consuptions. We might be forced to do an estimate eventually (?)

**Comment by MattiaSilvestri** [comment]
So in the docs they write: "_Please note that the reported energy consumption is not only the energy consumption of the code you are running. This includes the global energy consumption of all the process running on the machine during this period, thus including the operating system and other applications._" My idea would be to check their github page (https://github.com/powerapi-ng/pyJoules) and see how do they manage to get the general power consumption, then we can tweak it for our needs.  

Btw it's true that it doesn't seem trivial to get watt/h consumption, if we want a cumulative measure of the consumption from system startup we might see if we manage to get a sort of history of cpu and ram usage sensors and use this to estimate the consuption. Or we can decide that our program doesn't work retroactively and it calculate consumption only while it's running, but in this case it's basically a clone of pyjoules. I think for now a good beginning would be to write a program that estimate the power consumption based on sensors history (if there is one) and output the estimate as a static number, in the future we can think of running the program in the background and have it to continuously record the consumption, what to you think? Even tho I doubt that there is such a thing as sensors history...

**Comment by MattiaSilvestri** [comment]
Linux terminal-based apps that already perform this task: 
- https://github.com/ColinIanKing/powerstat
- https://github.com/fenrus75/powertop

**Comment by FrnRmn** [comment]
I think all of them rely on Intel RAPL. I have an AMD :/
I think it will be really hard to have something like that available for any hardware and for any os.

I don't want to be negative, but maybe we need to reconsider our project targets ✌️

**Comment by FrnRmn** [comment]
Btw, something similar to take inspiration from: https://pypi.org/project/energyusage/  (still for Intel CPU)

**Comment by MattiaSilvestri** [comment]
> I think all of them rely on Intel RAPL. I have an AMD :/ I think it will be really hard to have something like that available for any hardware and for any os.
> 
> I don't want to be negative, but maybe we need to reconsider our project targets v

Mmmm I didn't consider it, but yeah I agree that portability might be an issue for this kind of computation...


> Btw, something similar to take inspiration from: https://pypi.org/project/energyusage/ (still for Intel CPU)

Oh wow that's super cool! Definitely useful.

**Comment by FrnRmn** [comment]
New plan.

We are not going to rely on Intel RAPL. Other CPUs seem to lack a system so precise to measure energy consumption. However, we could make an estimate that can generalize to all types of processors.

- Get the current CPU model
- Get TDP associated to this CPU model
- Get CPU usage percentage
- Combine usage with TDP to estimate energy consumed
