### ISSUE TITLE
selenium chrome driver update

### ISSUE THREAD

**Issue by giulianogiari** [MattiaSilvestri/energy-monitor#27]
the function chrome_browser_setup in scraping.py stopped working, probably due to an update in chromedriver url.
this seems to be a common issue (e.g., https://stackoverflow.com/questions/76727774/selenium-webdriver-chrome-115-stopped-working) but needs to be fixed in order for the program to work. 
some suggested solutions from stackoverflow are not working:
- updated webdriver_manager (4.0.0) and selenium (4.10.0)
- downloaded an older version of chromedriver (114) but is not compatible with local chrome version

**Comment by FrnRmn** [comment]
Creating our simple database for TDPs to pack with the app is becoming more and more appealing :p
