### ISSUE TITLE
Define directory structure

### ISSUE THREAD

**Issue by FrnRmn** [MattiaSilvestri/energy-monitor#4]
This is what we were considering:

-- src
&nbsp;&nbsp;&nbsp;&nbsp;| -- main.py
-- package
&nbsp;&nbsp;&nbsp;&nbsp;| -- init.py
&nbsp;&nbsp;&nbsp;&nbsp;| -- utils.py
-- tests
&nbsp;&nbsp;&nbsp;&nbsp;| -- test_something.py
-- other files (readme, config...)

- https://stackoverflow.com/questions/193161/what-is-the-best-project-structure-for-a-python-application
- https://stackoverflow.com/questions/72712965/does-the-src-folder-in-pypi-packaging-have-a-special-meaning-or-is-it-only-a-co 

**Some other references on how to structure those projects?**

My doubt is whether _"package/"_ should be contained inside _"scr/"_, and whether _"main.py"_ should be contained inside _"package/"_.

-- src
&nbsp;&nbsp;&nbsp;&nbsp;| -- package
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| -- init.py
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| -- main.py
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| -- utils.py
-- tests
&nbsp;&nbsp;&nbsp;&nbsp;| -- test_something.py
-- other files (readme, config...)

**Comment by MattiaSilvestri** [comment]
I would keep the main.py in the src folder but out of the package folder. In the package I would just put custom modules we defined and I would give the package folder a meaningful name like "em" (energy monitor) or something like that. I would keep the README directly in the root folder, so not in any subfolder and the config files in a "config" folder. Later we can create a "bin" folder if we understand how to compile a python code to binary. So my idea is:

/energy-monitor (root)
    - README.md
    - setup.py (for later)
    /src
        - main.py
        /em
            - init.py
            - some_modules.py
    /bin
        - energy-monitor
    /tests
        - some_tests.py
    /config
        - config
    /doc
        - documentation

**Comment by MattiaSilvestri** [comment]
I would keep the main.py in the src folder but out of the package folder. In the package I would just put custom modules we defined and I would give the package folder a meaningful name like "em" (energy monitor) or something like that. I would keep the README directly in the root folder, so not in any subfolder and the config files in a "config" folder. Later we can create a "bin" folder if we understand how to compile a python code to binary. So my idea is:

- energy-monitor/ (root)
    README.md
    setup.py (for later)
    - src/
        main.py
        - em/
            init.py
            some_modules.py
    - bin/
        energy-monitor
    - tests/
        some_tests.py
    - config/
        config
    - doc/
        documentation

**Comment by MattiaSilvestri** [comment]
I'm gonna take care of this.
