### ISSUE TITLE
Call CPU Data API

### ISSUE THREAD

**Issue by FrnRmn** [MattiaSilvestri/energy-monitor#8]
https://rapidapi.com/ranjian0/api/cpu-data/details

**Comment by FrnRmn** [comment]
Maybe there is a problem with the endpoint. Let's see if we can an answer here: https://rapidapi.com/ranjian0/api/cpu-data/discussions/41535

**Comment by giulianogiari** [comment]
we can download this info from the manufacturers websites 
for amd this is already available https://www.amd.com/en/products/specifications/processors while for intel there is one for each processor https://ark.intel.com/content/www/us/en/ark.html#@Processors
the idea is to download the csv corresponding to the users' processor (maybe already during install?) and convert it to json for storage. this file will contain the details of the users' processor
